#!/bin/bash
set -euo pipefail

echo "=== Frontdoor Uninstaller ==="

# --- Defaults ---
INSTALL_DIR="/opt/frontdoor"
SERVICE_NAME="frontdoor"
PURGE=false

# --- Argument parser ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --purge)
            PURGE=true
            shift
            ;;
        *)
            echo "Unknown argument: $1" >&2
            echo "Usage: $0 [--purge]" >&2
            exit 1
            ;;
    esac
done

# --- Stop service ---
echo "Stopping $SERVICE_NAME service..."
if systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
    systemctl stop "$SERVICE_NAME"
    echo "  Stopped $SERVICE_NAME"
else
    echo "  $SERVICE_NAME is not active, skipping stop"
fi

if systemctl is-enabled --quiet "$SERVICE_NAME" 2>/dev/null; then
    systemctl disable "$SERVICE_NAME"
    echo "  Disabled $SERVICE_NAME"
else
    echo "  $SERVICE_NAME is not enabled, skipping disable"
fi

# --- Remove unit file ---
echo "Removing systemd unit file..."
if [ -f "/etc/systemd/system/$SERVICE_NAME.service" ]; then
    rm "/etc/systemd/system/$SERVICE_NAME.service"
    echo "  Removed /etc/systemd/system/$SERVICE_NAME.service"
else
    echo "  Unit file not found, skipping"
fi
systemctl daemon-reload
echo "  Reloaded systemd daemon"

# --- Purge or note ---
if [ "$PURGE" = true ]; then
    echo ""
    echo "=== Purging data (--purge specified) ==="

    # Remove application directory
    echo "Removing $INSTALL_DIR..."
    rm -rf "$INSTALL_DIR"
    echo "  Removed $INSTALL_DIR"

    # Remove self-signed certificates generated by installer
    echo "Removing self-signed certificates..."
    rm -f /etc/ssl/self-signed/*.crt /etc/ssl/self-signed/*.key
    echo "  Removed /etc/ssl/self-signed/*.crt and *.key"

    echo ""
    echo "NOTE: The following are NOT removed by this script:"
    echo "  - Caddy (installed separately; uninstall it via your package manager)"
    echo "  - Tailscale certificates (/etc/ssl/tailscale/) -- managed by Tailscale"
    echo "  - Caddy conf.d snippets (/etc/caddy/conf.d/) -- may be used by other services"
    echo "  - Caddy main config (/etc/caddy/Caddyfile) -- may be used by other services"
else
    echo ""
    echo "NOTE: Application data in $INSTALL_DIR was NOT removed."
    echo "  Run with --purge to also remove $INSTALL_DIR and self-signed certificates."
fi

echo ""
echo "=== Uninstall complete ==="
